/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarImageCarousel: typeof import('./components/rental/CarImageCarousel.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    DocumentUpload: typeof import('./components/rental/DocumentUpload.vue')['default']
    FilterPanel: typeof import('./components/rental/FilterPanel.vue')['default']
    Hint: typeof import('./components/Hint.vue')['default']
    ListSnackBar: typeof import('./components/ListSnackBar.vue')['default']
    Notification: typeof import('./components/ui/Notification.vue')['default']
    RentalFooter: typeof import('./components/rental/RentalFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    SearchBar: typeof import('./components/rental/SearchBar.vue')['default']
    TableFilterForm: typeof import('./components/TableFilterForm.vue')['default']
    ToggleTheme: typeof import('./components/ui/ToggleTheme.vue')['default']
    UserModal: typeof import('./components/UserModal.vue')['default']
    VehicleCard: typeof import('./components/rental/VehicleCard.vue')['default']
  }
}
